name: OpenSSF Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: "0 8 * * 1"
  push:
    branches: [ "main", "master" ]

permissions: read-all

jobs:
  analysis:
    uses: ossf/scorecard-action/.github/workflows/analysis.yml@v2.4.3
